-- SGHVBDS.VW_ADM_MEDICO_ESPECIALIDAD source

CREATE OR REPLACE FORCE VIEW "SGHVBDS"."VW_ADM_MEDICO_ESPECIALIDAD" ("COD_ESPECIALIDAD", "ESPECIALIDAD", "COD_MEDICO", "MEDICO", "REGISTRO_MED") AS 
  SELECT A.ESPECIALIDAD AS COD_ESPECIALIDAD,
    E.E.DESCRIPCION AS ESPECIALIDAD,
    M.CODIGO AS COD_MEDICO,
    M.PRIMER_NOMBRE || CASE WHEN M.SEGUNDO_NOMBRE IS NOT NULL THEN M.SEGUNDO_NOMBRE ELSE '' END || ', ' 
    || M.PRIMER_APELLIDO || CASE WHEN M.SEGUNDO_APELLIDO IS NOT NULL THEN M.SEGUNDO_APELLIDO ELSE '' END  AS MEDICO,
    CASE WHEN M.REG_MEDICO IS NULL THEN M.CODIGO ELSE M.REG_MEDICO END AS REGISTRO_MED

FROM TBL_ADM_MEDICO_ESPECIALIDAD A
LEFT JOIN TBL_ADM_MEDICO M ON A.MEDICO = M.CODIGO
LEFT JOIN TBL_ADM_ESPECIALIDAD_MEDICA E ON A.ESPECIALIDAD = E.CODIGO;